### PR TITLE
Move WP template to a subdirectory

### PR DESCRIPTION
**Pull request by szepeviktor**
@aristath What do you think about it?

WordPress core finds it inside a subdir making the root clean.

### CODE REVIEW

**Comment by szepeviktor** [comment]
kép

**Comment by aristath** [comment]
Hmmmm I don't get it... How would this work?
From what I know, WP-Core doesn't check inside a `template` folder in the theme :thinking:

**Comment by szepeviktor** [comment]
I say: Try it out!
Create a simple theme with only functions.php, style.css and index.php in /template subdir
and see what is happening in `/wp-admin/themes.php` :)

**Comment by szepeviktor** [comment]
...or look at the code:

https://github.com/WordPress/WordPress/blob/26bda18a23174afb048afbe62296c76a62add542/wp-includes/theme.php#L517

**Comment by aristath** [comment]
Yeah, but that is seen as a different theme!
If someone has the current version of Gridd installed, then on update we can't move files to a subfolder 'cause then WP errors thinking that the previous theme doesn't exist (which techically is correct).

**Comment by szepeviktor** [comment]
>  If someone has the current version of Gridd installed, then on update we can't move files to a subfolder 'cause then WP errors thinking that the previous theme doesn't exist (which techically is correct).

That is true, this is a breaking change.

**Comment by aristath** [comment]
I'm afraid we can't really do this... :(
If it was a new theme then it would be possible but not at this point.
I'll go ahead and close this one

**Comment by szepeviktor** [comment]
Okay.

I'm currently researching this area: separating files in WP themes.

**Pull request closed without merging**
